
name: Deploy Node Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. تحميل الكود
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. تثبيت Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. تثبيت dependencies
      - name: Install dependencies
        run: npm install

      # 4. (اختياري) تشغيل build
      - name: Build
        run: echo "No build step"

      # 5. Deploy عبر SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/node/app
            git pull origin main
            npm install
            pm2 restart all
